name: HolyKits
version: '1.0'
main: ru.nezxenka.holykits.HolyKits
api-version: 1.16
author: nezxenka
libraries:
  - com.h2database:h2:1.4.200

commands:
  kit:
    description: Получить набор
    usage: /kit <название>
  kitadmin:
    description: Управление наборами
    usage: /kitadmin <subcommand>

permissions:
  holykits.admin:
    description: Доступ к админ-командам наборов
    default: op
  holykits.bypass:
    description: Позволяет брать наборы без кулдауна
    default: op
  holykits.kit.*:
    description: Доступ ко всем наборам
    default: op